//
// Generated file, do not edit! Created by opp_msgc 4.2 from linklayer/can/arb.msg.
//

#ifndef _ARB_M_H_
#define _ARB_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>linklayer/can/arb.msg</tt> by opp_msgc.
 * <pre>
 * message ArbMsg{
 * 	int id;		
 * 	int node;	
 * 	bool rtr;	
 * 	bool remotesent; 
 * 	simtime_t signInTime;	
 * }
 * </pre>
 */
class ArbMsg : public ::cMessage
{
  protected:
    int id_var;
    int node_var;
    bool rtr_var;
    bool remotesent_var;
    simtime_t signInTime_var;

  private:
    void copy(const ArbMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ArbMsg&);

  public:
    ArbMsg(const char *name=NULL, int kind=0);
    ArbMsg(const ArbMsg& other);
    virtual ~ArbMsg();
    ArbMsg& operator=(const ArbMsg& other);
    virtual ArbMsg *dup() const {return new ArbMsg(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getId() const;
    virtual void setId(int id);
    virtual int getNode() const;
    virtual void setNode(int node);
    virtual bool getRtr() const;
    virtual void setRtr(bool rtr);
    virtual bool getRemotesent() const;
    virtual void setRemotesent(bool remotesent);
    virtual simtime_t getSignInTime() const;
    virtual void setSignInTime(simtime_t signInTime);
};

inline void doPacking(cCommBuffer *b, ArbMsg& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, ArbMsg& obj) {obj.parsimUnpack(b);}


#endif // _ARB_M_H_
