//
// Generated file, do not edit! Created by opp_msgc 4.3 from linklayer/can/err.msg.
//

#ifndef _ERR_M_H_
#define _ERR_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0403
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>linklayer/can/err.msg</tt> by opp_msgc.
 * <pre>
 * message ErrorFrame{
 * 	int id;		
 * 	int node;	
 * 	int kind; 
 * 	int pos;	
 * }
 * </pre>
 */
class ErrorFrame : public ::cMessage
{
  protected:
    int id_var;
    int node_var;
    int kind_var;
    int pos_var;

  private:
    void copy(const ErrorFrame& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ErrorFrame&);

  public:
    ErrorFrame(const char *name=NULL, int kind=0);
    ErrorFrame(const ErrorFrame& other);
    virtual ~ErrorFrame();
    ErrorFrame& operator=(const ErrorFrame& other);
    virtual ErrorFrame *dup() const {return new ErrorFrame(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getId() const;
    virtual void setId(int id);
    virtual int getNode() const;
    virtual void setNode(int node);
    virtual int getKind() const;
    virtual void setKind(int kind);
    virtual int getPos() const;
    virtual void setPos(int pos);
};

inline void doPacking(cCommBuffer *b, ErrorFrame& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, ErrorFrame& obj) {obj.parsimUnpack(b);}


#endif // _ERR_M_H_
